### PR TITLE
Support for upsert operation on an object level

### PR DESCRIPTION
**Pull request by j-fischer**
Introduced a new field in the object configuration call `externalIdField`, which will trigger an `upsert` operation for the bulk API load using its value as the primary ID identifier. 
Note that the `records` array had to be cloned to remove the ID in order to succeed with the `upsert` since JSForce does remove it automatically for `insert` operations but not for `upsert`. Removing the Id property on the original array would break the ID mapping logic. 
It's very much possible that I missed some changes in the code base. Please let me know if that is the case. 

Would be great to see this in a new version sometime soon. ;) Thanks for this fantastic plugin!

Cheers!

### CODE REVIEW

**Comment by j-fischer** [comment]
@eltoroit Is there any interest to adopt PR for `upsert` operations?

**Comment by eltoroit** [comment]
@j-fischer sorry for the late reply. I have been extremely busy and with too many projects, so I had not had a chance to look at this. I was having some performance issues with ETCopyData and I decided to use SOAP API rather than BULK API and the speed got improved quite a bit. But now your changes have some conflicts because we change the same lines.

**Comment by j-fischer** [comment]
I will have to check whether if and how I can adopt your changes in my fork and will try to update the my PR after. It may take a bit since I am pretty busy myself these days. Trying to get this done before the end of the year. Could you please confirm that you are interested in adopting the change?

**Comment by j-fischer** [comment]
Will create another PR with the fixes for the merge conflicts.

**Comment by eltoroit** [comment]
Thanks for helping out, the pull requested has been merged

**Pull request merged**
